// Code generated by "stringer -type=TokenType"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[İllegal-1]
	_ = x[EOF-2]
	_ = x[LF-3]
	_ = x[At-4]
	_ = x[LBrace-5]
	_ = x[RBrace-6]
	_ = x[Comment-7]
	_ = x[String-8]
	_ = x[Assign-9]
}

const _TokenType_name = "İllegalEOFLFAtLBraceRBraceCommentStringAssign"

var _TokenType_index = [...]uint8{0, 8, 11, 13, 15, 21, 27, 34, 40, 46}

func (i TokenType) String() string {
	i -= 1
	if i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
